from numpy import vstack

import initMolecule

import builder.utils_builder as UB                        # Import all the functions to do with creating the nucleic acid duplex
import builder.utils_of_utils_builder as utilsUB          # Import all smaller functions
from ducquelib.library import TABLE_NUCLEOTIDES, TABLE_CONFORMATIONS # Import the nucleic acid tablesd

import systemsDucque as SD

""" Create dictionary of the filename and their molecule code """

TN = TABLE_NUCLEOTIDES   # Creates an object of the nucleic acid dictionary for the leading strand
TC = TABLE_CONFORMATIONS     # Creates an object of the nucleic acid dictionary for the complementary strand



def Architecture(lead_nucleic_acid_list, complement, outfile):
    """ This function contains all the functions to create the nucleic acid duplex.

    First up, a bottom-up approach is applied when building the nucleic acid single strand.

    A complementary strand is generated by fitting the nucleosides and linker elements, in a bottom-up approach, to the leading strand.

    Finally, a pdb is outputted, with the two chains in present. """

    # Reverse the list order, because we build the nucleoside from the bottom up.
    lead_nucleic_acid_list.reverse()

    CONF_LIST = [[], []]    # Initialise the list of conformations being parsed from
    LINK_LIST = [[], []]    # Initialise the list of linkers being parsed from
    index_lead = 0          # Initiate the index counter for the leading strand. 

    # Parse the first nucleotide in the list.
    nucleic_acid = lead_nucleic_acid_list[0]

    ## START THE LEADING STRAND
    # Parse dictionary for the correct filename; input(DT) - output(dna_thymidine.json). This also parses the correct linker.
    nucleoside = initMolecule.Nucleoside(TN[nucleic_acid][0]) ; index_lead += nucleoside.mol_length
    linker = initMolecule.Linker(TN[nucleic_acid][1]) ; index_lead += linker.mol_length
    CONF_LIST[0].append(nucleoside.filename)    # Append name of file to list
    LINK_LIST[0].append(linker.filename)    # Append name of file to list

    # Position the linker moiety on the nucleoside.
    leading_strand = UB.position_phosphate_linker(nucleoside, nucleoside.array, linker)

    num_nucl = 1 # Initiate a building block counter

    # This for loop positions the subsequent nucleotides of the leading strand.
    for NA in range(1, len(lead_nucleic_acid_list)):

        # Import the next nucleoside and create an object
        nextnuc_acid = lead_nucleic_acid_list[NA]

        # Parse the dictionary for the previous nucleotide, to append the next nucleotide onto.
        previous_nucleic_acid = lead_nucleic_acid_list[NA - 1]
        # Parse the correct nucleoside and linker and create them as objects
        prevnuc, prevlink = initMolecule.Nucleoside(TN[previous_nucleic_acid][0]), initMolecule.Linker(TN[previous_nucleic_acid][1])

        # Assert which conformation fits the strand better and take that one and use it build the nucleotide
        conformations = TC[nextnuc_acid]
        nextnuc_asserted_conf = UB.assert_leading_strand_nucleotide_conformation(conformations, prevnuc, prevlink, leading_strand)
        nextnuc = initMolecule.Nucleoside(nextnuc_asserted_conf) ; index_lead += nextnuc.mol_length
        nextlink = initMolecule.Linker(TN[nextnuc_acid][1]) ; index_lead += nextlink.mol_length

        CONF_LIST[0].append(nextnuc.filename)   # Append name of file to list

        # Position the following nucleoside in the sequence
        next_nucleoSIDE_positioned = utilsUB.position_next_nucleoside(nextnuc, prevnuc, prevlink, leading_strand)

        # Position the following linker to create a nucleotide array
        if not (NA + 1) == len(lead_nucleic_acid_list):
            # If this is not the last nucleoside in the sequence, build a linker onto it.
            next_nucleoTIDE_positioned = UB.position_phosphate_linker(nextnuc, next_nucleoSIDE_positioned, nextlink)
            LINK_LIST[0].append(nextlink.filename)   # Append name of file to list

            # Create a tuple of the two arrays and stack them. This becomes the leading strand upon which we continue appending nucleotides.
            leading_strand = vstack((next_nucleoTIDE_positioned, leading_strand))
        else:
            # Leave the object as a nucleoside, since it is the last one in the sequence. Create a tuple of the two arrays to finalise the leading strand.
            leading_strand = vstack((next_nucleoSIDE_positioned, leading_strand))
            # Substract the last linker's molecule size, since it is not included at the end of the leading strand. This index_lead is now set correctly to start the complementary strand build.
            index_lead -= nextlink.mol_length

        num_nucl += 1


    ### GENERATE THE COMPLEMENTARY STRAND
    # a list of complementary nucleotides
    compl_lead_nucleic_acid_list = UB.generate_complementary_sequence(lead_nucleic_acid_list, complement)

    # Import the first two leading strand nucleosides, but as a list
    leading_nucleosides = [TN[lead_nucleic_acid_list[0]], TN[lead_nucleic_acid_list[1]]]

    # Both compl1 and compl2 are a list of json filenames. These become instanced object in the function 'assert_starting_bases_..._strand()'
    compl1, compl2 = TC[compl_lead_nucleic_acid_list[0]], TC[compl_lead_nucleic_acid_list[1]]
    compl2_linker = initMolecule.Linker(TN[compl_lead_nucleic_acid_list[1]][1])
    complementary_strand, index_lead, compl1_nuc, compl2_nuc = UB.assert_starting_bases_of_complementary_strand(compl1, compl2, compl2_linker, leading_nucleosides, leading_strand, index_lead)

    CONF_LIST[1].extend([compl1_nuc.filename, compl2_nuc.filename])
    LINK_LIST[1].append(compl2_linker.filename)
    index_compl = complementary_strand.shape[0]                 # Increment the index_complementary integer

    # Add subsequent complementary nucleotides
    for cNA in range(2, len(compl_lead_nucleic_acid_list)):
        # Parse the information of the leading strand nucleotide we want to fit the complementary nucleoside against
        lead_nextnuc_acid = lead_nucleic_acid_list[cNA]
        lead_nextnuc, lead_nextlinker = initMolecule.Nucleoside(TN[lead_nextnuc_acid][0]), initMolecule.Linker(TN[lead_nextnuc_acid][1])
        index_lead -= (lead_nextnuc.mol_length + lead_nextlinker.mol_length)

        # Parse the name of the files of the different conformations of the complementary nucleic acid
        compl_nextnuc_acid = compl_lead_nucleic_acid_list[cNA]
        conformations, compl_nextlinker = TC[compl_nextnuc_acid], initMolecule.Linker(TN[compl_nextnuc_acid][1])

        # Parse the previous complementary nucleic acid
        prev_compl_nextnuc_acid = compl_lead_nucleic_acid_list[cNA - 1]
        prev_compl_nuc, prev_compl_linker = initMolecule.Nucleoside(TN[prev_compl_nextnuc_acid][0]), initMolecule.Linker(TN[prev_compl_nextnuc_acid][1])
        index_compl -= (prev_compl_linker.mol_length + prev_compl_nuc.mol_length)

        fitted_nextnuc = UB.assert_possible_base_conformations_and_fit(lead_nextnuc, leading_strand, conformations, compl_nextlinker, complementary_strand,
                                                                                                  prev_compl_nuc, prev_compl_linker, index_lead, index_compl)
        #complementary_strand = vstack((complementary_strand, compl_nextnuc_arr))
        complementary_strand = vstack((complementary_strand, fitted_nextnuc.array))
        CONF_LIST[1].append(fitted_nextnuc.filename)
        LINK_LIST[1].append(compl_nextlinker.filename)

        #index_compl += (prev_compl_linker.mol_length + prev_compl_nuc.mol_length) + compl_nextnuc_arr.shape[0]
        index_compl += (prev_compl_linker.mol_length + prev_compl_nuc.mol_length) + fitted_nextnuc.array.shape[0]


    # Orient the linker moieties better in each nucleotide
    leading_strand, complementary_strand = UB.orient_the_linker_moieties_better(CONF_LIST, LINK_LIST, leading_strand, complementary_strand)


    #------------------------ CREATE THE PDB THAT GOES WITH ARRAY INPUTTED -------------------#
    UB.create_PDB_from_array_final(outfile, leading_strand, lead_nucleic_acid_list, complementary_strand, compl_lead_nucleic_acid_list)
    SD.print_dupl_ln(num_nucl)

